### ISSUE TITLE
Getting error when trying to do region select screenshot that is copied to stdout

### ISSUE THREAD

**Issue by rooiratel** [waycrate/wayshot#36]
When I run `wayshot --stdout -s "$(slurp)" | wl-copy` or `wayshot -s "$(slurp -p)" --stdout | wl-copy`

I get this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/wayshot.rs:65:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When I run with RUST_BACKTRACE=full I get :

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/wayshot.rs:65:69
stack backtrace:
   0:     0x55823ae7953d - <unknown>
   1:     0x55823ae96ccc - <unknown>
   2:     0x55823ae76d71 - <unknown>
   3:     0x55823ae7abc5 - <unknown>
   4:     0x55823ae7a8e6 - <unknown>
   5:     0x55823ae7b156 - <unknown>
   6:     0x55823ae7b047 - <unknown>
   7:     0x55823ae799f4 - <unknown>
   8:     0x55823ae7ad79 - <unknown>
   9:     0x55823ad965d3 - <unknown>
  10:     0x55823ad96663 - <unknown>
  11:     0x55823adbaa33 - <unknown>
  12:     0x55823adb31d6 - <unknown>
  13:     0x55823adcdcd3 - <unknown>
  14:     0x55823add67d9 - <unknown>
  15:     0x55823ae71a0e - <unknown>
  16:     0x55823adb47c2 - <unknown>
  17:     0x7f03885cf790 - <unknown>
  18:     0x7f03885cf84a - __libc_start_main
  19:     0x55823ad96815 - <unknown>
  20:                0x0 - <unknown>
```

**Comment by Shinyzenith** [comment]
High, are you using the bin package or the git package? Slurp default format parsing was introduced in master branch recently and hasn't been tagged.

**Comment by rooiratel** [comment]
I was using the bin package. Thanks, I'll try the git package.
