### ISSUE TITLE
Build fails on latest: "No such file or directory"

### ISSUE THREAD

**Issue by zenzoa** [waycrate/wayshot#39]
When I try to install via `wayshot-git` on Arch Linux or build it after cloning the repo, I get this error:
```
error: failed to run custom build command for `wayshot v1.2.2 (/home/sg/Downloads/wayshot/wayshot)`

Caused by:
  process didn't exit successfully: `/home/sg/Downloads/wayshot/target/release/build/wayshot-2c57142df8cfca8d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', wayshot/build.rs:54:32
  stack backtrace:
     0:     0x56493fc559da - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x56493fc559da - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x56493fc559da - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x56493fc559da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x56493fc72a9e - core::fmt::write::h5a4baaff1bcd3eb5
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
     5:     0x56493fc53805 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
     6:     0x56493fc557a5 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x56493fc557a5 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x56493fc56dff - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
     9:     0x56493fc56b3b - std::panicking::default_hook::ha3500da57aa4ac4f
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
    10:     0x56493fc573a8 - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
    11:     0x56493fc572a9 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
    12:     0x56493fc55e46 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
    13:     0x56493fc56fb2 - rust_begin_unwind
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
    14:     0x56493fc09413 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
    15:     0x56493fc09803 - core::result::unwrap_failed::hdff5465d74574b44
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
    16:     0x56493fc0fbac - core::result::Result<T,E>::unwrap::h6a0b186923f2584c
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1090:23
    17:     0x56493fc0e57a - build_script_build::read_and_replace_by_ext::h4f1badb8c8044035
                                 at /home/sg/Downloads/wayshot/wayshot/build.rs:54:17
    18:     0x56493fc0dbf3 - build_script_build::main::hd6a68b3c3badc776
                                 at /home/sg/Downloads/wayshot/wayshot/build.rs:23:44
    19:     0x56493fc1172b - core::ops::function::FnOnce::call_once::h40ed78a42bf7b569
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
    20:     0x56493fc1523e - std::sys_common::backtrace::__rust_begin_short_backtrace::h5dda9afabc2093ce
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:134:18
    21:     0x56493fc0b9b1 - std::rt::lang_start::{{closure}}::h6767f225fc8f766a
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:166:18
    22:     0x56493fc5114c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd6efcd3bec896f2c
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
    23:     0x56493fc5114c - std::panicking::try::do_call::hce04e543bb1f4cbb
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    24:     0x56493fc5114c - std::panicking::try::h3342dd4e1f680968
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    25:     0x56493fc5114c - std::panic::catch_unwind::h148ce1e59ac0cee7
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    26:     0x56493fc5114c - std::rt::lang_start_internal::{{closure}}::h25f9dda2057a67fe
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
    27:     0x56493fc5114c - std::panicking::try::do_call::h7caaaeaf9401650b
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    28:     0x56493fc5114c - std::panicking::try::he7d15285746cbbc2
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    29:     0x56493fc5114c - std::panic::catch_unwind::h89fb4f50c0301fe0
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    30:     0x56493fc5114c - std::rt::lang_start_internal::h078acd489417d3c1
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
    31:     0x56493fc0b98a - std::rt::lang_start::h97bd7c64a5c463fb
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:165:17
    32:     0x56493fc0eb6e - main
    33:     0x7f539fa0f850 - <unknown>
    34:     0x7f539fa0f90a - __libc_start_main
    35:     0x56493fc099e5 - _start
    36:                0x0 - <unknown>
```

**Comment by zenzoa** [comment]
This appears to be due to the [latest commit](https://github.com/waycrate/wayshot/commit/ea69559bdd78e7d3ed85eba0a59cc19dae6343fd). Resetting to [the commit before](https://github.com/waycrate/wayshot/commit/a0c8e39d982f27dd94306d450903ba47d9abe026) that solves the issue for me.
